### ISSUE TITLE
Cmake issue

### ISSUE THREAD

**Issue by mkcisse** [galeone/openat#4]
Hi, I tried to compile openat with the following commands:
`mkdir build`
`cd build`
`cmake ..`
The Makefile does noot appear in  the directory.
How to compile ths library ?

**Comment by galeone** [comment]
Hi @mkcisse 

The commands are correct. Have you also installed all the required dependencies and cloned the submodules too?

Which OS are you using?

I'm testing it right now locally and the following command sequence builds the library correctly.

Using archlinux I had to install first some system dependency:

```
sudo pacman -S spdlog gumbo-parser nlohmann-json
yay -S libcurlpp
#using yay because is available in the AUR, however you can install from the repo itself, going into
# libs/curlpp/ and giving mkdir build; cd build; cmake ..; make; sudo make install
```

Then clone the repo and install other dependencies I can't find on the repositories (that are shipped with openat).

```
git clone --recurse-submodules git@github.com:galeone/openat.git
cd openat/libs/gumbo/query/
```

Here's I just noticed there is a problem what make, and we have to fix it manually.
Open the file `cmake/FindGumbo.cmake` and comment the lines

```
#find_library(Gumbo_static_LIBRARY
#  NAMES libgumbo.a libgumbo_static.a gumbo.a gumbo_static.a libgumbo.lib libgumbo_static.lib gumbo.lib gumbo_static.lib
#  PATHS ${Gumbo_PKGCONF_LIBRARY_DIRS}
#)
```
and also change this line in this way:

```
# (just comment out Gumbo_static_LIBRARY)
set(Gumbo_PROCESS_LIBS Gumbo_LIBRARY)# Gumbo_static_LIBRARY)
```

After that
```
cd build
cmake ..
make
sudo make install
# now we have gumbo query installed in the system
```

Now we are ready to build openat, so go back go the openat repo, and

```
mkdir build
cd build
make ..
make
```

**Comment by mkcisse** [comment]
> Which OS are you using?
Ubuntu 18..04 LTS bionic

This is the error message:
`
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message)
`

**Comment by galeone** [comment]
Yes, is the error you get while building gumbo query - manually apply the fix as I described (commenting the lines) and it should work

**Comment by mkcisse** [comment]
It works !
However, i have the same issue with : 
`
CMake Error at src/CMakeLists.txt:16 (find_package):
  By not providing "Findnlohmann_json.cmake" in CMAKE_MODULE_PATH this
`
I already ran : `apt-get install -y nlohmann-json-dev`

**Comment by galeone** [comment]
uhm.. it should work - the integration with cmake of the JSON library is made exactly as suggested from the documentation https://github.com/nlohmann/json#cmake

However, looking at some comments into that repo, I can see that is a pretty common issue: https://github.com/nlohmann/json/issues/1977#issuecomment-612888612

Maybe on Ubuntu the nlohmann-json-dev package is installed in some non standard location?

I don't know I'm sorry, and I also don't have an ubuntu machine to use to test

**Comment by mkcisse** [comment]
I downloaded and compiled nlohmann_json from git repo: `https://github.com/nlohmann/json`
But another issue:
`
CMake Error at src/CMakeLists.txt:21 (add_library):
  Target "openat" links to target "Threads::Threads" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
`

**Comment by nlohmann** [comment]
In order to asses your issue, we need the following information:

- What is the issue you have?

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

- What is the expected behavior?

- And what is the actual behavior instead?

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

**Comment by mkcisse** [comment]
I got it. The issue comes from the default nlohmann_json on Ubuntu. No problem when I compiled nlohmann_json. This is the  last result of `cmake ..` command:

`-- Looking for pthread_create in pthreads`
`-- Looking for pthread_create in pthreads - not found`
`-- Looking for pthread_create in pthread`
`-- Looking for pthread_create in pthread - found`
`-- Found Threads: TRUE `
`-- Configuring done`
`CMake Error at src/CMakeLists.txt:21 (add_library):`
`  Target "openat" links to target "Threads::Threads" but the target was not`
`  found.  Perhaps a find_package() call is missing for an IMPORTED target, or`
`  an ALIAS target is missing?`

`CMake Error at tests/CMakeLists.txt:10 (add_executable):`
`  Target "openat_tests" links to target "Threads::Threads" but the target was`
`  not found.  Perhaps a find_package() call is missing for an IMPORTED`
`  target, or an ALIAS target is missing?`

`-- Generating done`
`-- Build files have been written to: /home/mkcisse/openat/build`

**Comment by galeone** [comment]
Happy you solved with the JSON stuff!

For this last problem, yes this is a bug in my cmake. I forgot to add the line `find_package(Threads)`.

I fixed it in the last commit on master branch. Update the repo to the latest version (`git pull origin master`) and try again :+1:
